== Seedwing Policy CLI

The Seedwing Policy CLI provides access to the functionality of the Seedwing Policy Engine without requiring access to a running Policy Server.

The primary command is `swio`, derived from the domain of `seedwing.io`.

=== General Usage

Have a look at the xref:examples.adoc[examples] for how to use it.

==== Configuration: `-f <FILE_OR_DIR>`

A single optional configuration may be specified by providing either a full path to a file or a path to a directory containing a `Seedwing.toml`.

The contents of the file should match the xref::seedwing_toml.adoc['Seedwing.toml'] format.

==== Policy Directories: `-p <DIR>`

Zero or more policy directories may be specified using the `-p <DIR>` argument.

==== Data Directories: `-d <DIR>`

Zero or more data directories may be specified using the `-d <DIR>` argument.

==== Commands

Subcommands are used to adjust the mode of function.

* xref:verify.adoc[`verify`] - To verify successful parsing and compilation of a set of policies.
* xref:eval.adoc[`eval`] - To evaluate an input against policies.
* xref:serve.adoc[`serve`] - To launch an API and UI server.
* xref:test.adoc[`test`] - To test policies against inputs.
* xref:bench.adoc[`bench`] - To benchmark a policy against an input.
