[build]
release = true

[serve]
port = 8010
open = false

[[proxy]]
backend = "http://localhost:8080/api/"

[[proxy]]
backend = "http://localhost:8080/openapi/"

[[proxy]]
backend = "ws://localhost:8080/stream/"
ws = true
