= `test`

The `test` command runs a set of inputs against policies to test that their output is as expected.

== Usage

=== Input test directory: `-t <DIR>`

The `-t <DIR>` argument specifies the a directory containing the root of a tree matching the xref:test_structure.adoc[test structure] and containing a suite of xref:test_case.adoc[test cases].

=== Pattern matching: `-m <MATCH>`

The `-m <MATCH>` argument may be used to specify a subset of tests to execute.

The `MATCH` argument prefix-matches against the name of the pattern under consideration joined with the named test.
There is no requirement that the `MATCH` argument be a complete name of a module, pattern or test.
Simple string-prefix matching occurs.

This argument may only be specified once.

For instance:

* `-m base64`: would match all tests for all patterns in the `base64` module.
* `-m base64::base64`: would match all tests for the `base64::base64` pattern.
* `-m base64::base64::valid-document`: would match exactly the `valid-document` test for `base64::base64`.



