#![recursion_limit = "1024"]
#![allow(clippy::needless_return)]
// The following two clippy configurations are to workaround warnings that are
// currently being generated by src/pages/mod.rs.
// TODO: figure out the cause of these warnings which I think might be caused
// by yew_nested_router::Target.
#![allow(clippy::wrong_self_convention)]
#![allow(clippy::redundant_closure)]

mod about;
mod app;
mod common;
mod console;
mod pages;
mod utils;

use wasm_bindgen::prelude::*;

#[cfg(not(debug_assertions))]
const LOG_LEVEL: log::Level = log::Level::Info;
#[cfg(debug_assertions)]
const LOG_LEVEL: log::Level = log::Level::Trace;

pub fn main() -> Result<(), JsValue> {
    wasm_logger::init(wasm_logger::Config::new(LOG_LEVEL));
    yew::Renderer::<app::Application>::new().render();
    Ok(())
}
